// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  ToDoList = 1,
  DoneContent = 2,
  Done = 3,
  PriorityA = 4,
  PriorityB = 5,
  PriorityC = 6,
  Description = 7,
  Project = 8,
  Context = 9,
  DueDate = 10,
  Content = 11,
  PriorityAContent = 12,
  PriorityBContent = 13,
  PriorityCContent = 14,
  NormalContent = 15,
  NewLine = 16
